remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme

title: "The VPF Grant: The Real Deal"
description: "A toolkit for Victorian game devs navigating the VPF grant."
show_downloads: false

github:

  repository_url: https://github.com/M7stic/HannahFlannery.github.io

  project_title: The VPF Grant - The Real Deal
